### ISSUE TITLE
Automatic register allocation

### ISSUE THREAD

**Issue by Immortalin** [xyproto/battlestar#1]
The LLVM IR automatically does register allocation, so does the PeachPy compiler. Perhaps battlestar can do something similar?

**Comment by xyproto** [comment]
Hello,

I was thinking of adding LLVM IR output and make LLVM handle it (since register allocation can be tricky, at least for optimal results), but attempting to implement it in battlestar would be fun.

Thanks for the suggestion, I'll keep it open as a feature request.

Cheers,
Alexander F Rødseth

**Comment by xyproto** [comment]
I've been thinking about this, and I just want Battlestar to be an alternative assembly syntax.

However, I wish to create another language in the future that has a register allocator.

Thanks for the input!
